version: 3
endpoint: https://learn-postgres.hasura.app
admin_secret: H94P5lMgO8u8dOF5IlG7FrbKM1yUNmdtaHwvou09EvUISGQT6XxIekqokC5zrtdV
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
